pipeline {
  agent{
    any{
      image 'node:lts-buster-slim'
      args '--user root -v /var/run/docker.sock:/var/run/docker.sock' // mount Docker socket to access the host's Docker daemon
    }
}
  
  
    stages {
        stage('checkout') {
            steps {
                // Get some code from a GitHub repository
                git 'https://github.com/akshu2430/simple-node-js-react-npm-app.git'
            }
        }
        
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
         
        
        stage('Deploy') {
            steps {
                    sh '''
                    cp -r /var/lib/jenkins/workspace/multibranch_pipeline/public/*.html /var/www/html
                    '''
            }
        }
    }
}
