pipeline {
    agent{
    any{
      image 'node:lts-buster-slim'
      args '--user root -v /var/run/docker.sock:/var/run/docker.sock' // mount Docker socket to access the host's Docker daemon
    }
}
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('Deliver for development') {
            when {
                branch 'dev'
            }
            steps {
               sh '''
                    cp -r /var/lib/jenkins/workspace/multibranch_pipeline/public/*.html /var/www/html
                    '''
            }
        }
        stage('Deploy for production') {
            when {
                branch 'prod'
            }
            steps {
                sh '''
                    cp -r /var/lib/jenkins/workspace/multibranch_pipeline/public/*.html /var/www/html
                    '''
            }
        }
    }
}
